export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';



export const OPEN_MODAL_EMAIL = 'OPEN_MODAL_EMAIL';
export const CLOSE_MODAL_EMAIL = 'CLOSE_MODAL_EMAIL';


export const OPEN_PANEL = 'OPEN_PANEL';
export const OPEN_PANEL_PATIENT = 'OPEN_PANEL_PATIENT';
export const CLOSE_PANEL_PATIENT = 'CLOSE_PANEL_PATIENT';




export const OPEN_PANEL_RMA = 'OPEN_PANEL_RMA';
export const CLOSE_PANEL_RMA = 'CLOSE_PANEL_RMA';



export const OPEN_EXPENSE_PANEL = 'OPEN_EXPENSE_PANEL';
export const CLOSE_EXPENSE_PANEL = 'CLOSE_EXPENSE_PANEL';

export const OPEN_PURCHASE_PANEL = 'OPEN_PURCHASE_PANEL';
export const CLOSE_PURCHASE_PANEL = 'CLOSE_PURCHASE_PANEL';
export const OPEN_CLIENT_PANEL = 'OPEN_CLIENT_PANEL';
export const CLOSE_CLIENT_PANEL = 'CLOSE_CLIENT_PANEL';

export const OPEN_SUBCONTRACT_PANEL = 'OPEN_SUBCONTRACT_PANEL';
export const CLOSE_SUBCONTRACT_PANEL = 'CLOSE_SUBCONTRACT_PANEL';
export const CLOSE_PANEL = 'CLOSE_PANEL';
export const COLLAPSE_PANEL = 'COLLAPSE_PANEL';
